- name: installing nginx
  ansible.builtin.package:
    name: nginx
    state: installed
- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
- name: import the roles from common
  ansible.builtin.import_role:
    name: common
    tasks_from: main

- name: extract the code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip #by default ansible thinks this is in ansible server
    dest: /usr/share/nginx/html
    remote_src: yes
- name: copy the conf file
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - Restart nginx

# - name: restart nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted